backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/resources/faq.md"
        label: "FAQ Page"
        name: "faq"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "faq"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Frequently Asked Question, name: faq, widget: list, fields: [{label: Question, name: question, widget: string}, {label: Answer, name: answer, widget: string}]}
      - file: "src/pages/resources/locations.md"
        label: "Locations Page"
        name: "locations"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "locations"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Location, name: locations, widget: list, fields: [{label: Location, name: location, widget: string}]}
      - file: "src/pages/resources/rentals.md"
        label: "Rentals Page"
        name: "rentals"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "rentals"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Rental Affiliate, name: affiliate, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Website, name: url, widget: string}, {label: Logo URL, name: logourl, widget: string}, {label: Boats 4 Rent, name: boats, widget: string}]}
      - file: "src/pages/resources/testimonials.md"
        label: "Testimonials Page"
        name: "testimonials"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "testimonials"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Testimonial, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      - file: "src/pages/gallery/index.md"
        label: "Image Gallery"
        name: "gallery"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery"}
          - {label: "Title", name: "title", widget: "string"}
